name: canyon-stock-check

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install requests

      - run: |
          while true
          do
            python canyon_check.py
            sleep 120
          done
